Revert "libcamera: Define packageconfig to enable rpi pipeline"
This reverts commit a27f10b76cb1dbf089a3f0980e97f1931b090f17.

This was backported to dunfell together with many other changes in:
https://github.com/agherzan/meta-raspberrypi/pull/754

but 202002 version in dunfell fails with:
ERROR: QA Issue: libcamera: configure was passed unrecognised options: pipelines [unknown-configure-option]

202008 version in gatesgarth is fine, it was added in March:
https://git.linuxtv.org/libcamera.git/commit/meson_options.txt?id=ee7e2c93dfbf34b3500c895115c516e5e90d3e31

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>