vc-graphics.inc: Skip ldflags insane check
Since these binaries are proprietary and we have no control over them,
skip this innsane check to avoid errors like:
ERROR: QA Issue: No GNU_HASH in the elf binary: '<binary>'

Signed-off-by: Andrei Gherzan <andrei@gherzan.ro>