webkitgtk: Remove -DUSE_GSTREAMER_GL=OFF for vc4graphics
This is no longer needed, on the contrary is fails the build for
webkitgtk

Fixes
webkitgtk-2.24.2/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1007:33: error: use of undeclared identifier 'TEXTURE_MAPPER_COLOR_CONVERT_FLAG'
|         m_textureMapperFlags |= TEXTURE_MAPPER_COLOR_CONVERT_FLAG;
|                                 ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>