userland: use default PACKAGE_ARCH
* drop MACHINE_ARCH which was added in:
  https://github.com/agherzan/meta-raspberrypi/commit/592274937b774b4d98045eef1ef820a5c27253fd
* the recipe is using MACHINE_FEATURES but if everybody either enables or disables vc4graphics
  for all rpi MACHINEs it isn't causing it to be MACHINE_ARCH any more than all other rpi
  overrides used in this layer.
* raspberrypi3-64 is the only one with vc4graphics by default, but it
  has different TUNE_PKGARCH than other rpi MACHINEs). Unfortunately not
  without its own set of issues:
  http://lists.openembedded.org/pipermail/openembedded-core/2019-April/281328.html
* fixes userland and everything which depends on it (qtbase, qtwebengine..)
  to be effectivelly MACHINE_ARCH

  === Comparing signatures for task do_package_write_ipk.sigdata between raspberrypi2 and raspberrypi3 ===
  ERROR: qtbase different signature for task do_package_write_ipk.sigdata between raspberrypi2 and raspberrypi3
  NOTE: Starting bitbake server...
  Hash for dependent task userland/userland_git.bb.do_packagedata changed from dcfe9e7982ce1e231f06293c1e568d77384f167358fe88debe761290483244a0 to baa4d4164b0045f46c966e773cfeeed87f2c491c3dbd368af7cf4cd63ce39177
  Unable to find matching sigdata for /OE/build/luneos-master/webos-ports/meta-raspberrypi/recipes-graphics/userland/userland_git.bb.do_packagedata with hashes dcfe9e7982ce1e231f06293c1e568d77384f167358fe88debe761290483244a0 or baa4d4164b0045f46c966e773cfeeed87f2c491c3dbd368af7cf4cd63ce39177

  ERROR: 1 errors found in /OE/build/luneos-master/webos-ports/tmp-glibc/sstate-diff/1555500556/signatures.raspberrypi3.do_package_write_ipk.sigdata.log

  bitbake-diffsigs tmp-glibc/sstate-diff/1555495762/r*/*/userland/do_fetch
  NOTE: Starting bitbake server...
  basehash changed from d767ab01261472a220e0ec80b01bc33e60764d56b5880ab3153afd42ea734703 to e57e594d7e4219f22778ccc5d8c102deeeaff64586e0f71cd90964fa2ace4e1c
  Variable MACHINE value changed from 'raspberrypi2' to 'raspberrypi3'

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>