u-boot: Backport patch to fix u-boot compilation without USB config
Raspberry Pi 4 doesn't have a working USB driver in u-boot. This makes
the defconfig not to enable the relevant config case which breaks the
build with:

error: expected '}' before
'BOOT_TARGET_DEVICES_references_USB_without_CONFIG_CMD_USB'

This was fixed in upstream and we backport the relevant commit.

Signed-off-by: Andrei Gherzan <andrei@balena.io>