userland: Fix POSIX compliance expectation
We have errors like below with glibc 2.22+

net_sockets_common.c:139:20: error: storage size of 'hints' isn't known
    struct addrinfo hints, *info, *p;
                        ^

newer glibc has now fixed the definitions of getaddrinfo and ilk to be
enabled with correct posix version.

Signed-off-by: Khem Raj <raj.khem@gmail.com>

(cherry picked from commit f188f3d756f59fb4dc64cc1a64263c2251f76ae5)
Signed-off-by: Petter Mabäcker <petter@technux.se>