Drop tslib from packageconfig.
yocto zeus has no tslib support anymore, so the build fails with:
ERROR: Nothing PROVIDES 'tslib' (but meta-qt5/recipes-qt/qt5/qtbase_git.bb DEPENDS on or otherwise requires it). Close matches:
  taglib
ERROR: Required build target 'qtbase' has no buildable providers.
Missing or unbuildable dependency chain was: ['qtbase', 'tslib']