packagegroup-rpi-test: use MACHINE_ARCH
* fixes this error reported by sstate-diff-machines.sh:
   === Comparing signatures for task do_package_write_ipk.sigdata between raspberrypi2 and raspberrypi3 ===                                                                                                                                                              |
  ERROR: packagegroup-rpi-test different signature for task do_package_write_ipk.sigdata between raspberrypi2 and raspberrypi3                                                                                                                                           |
  NOTE: Starting bitbake server...                                                                                                                                                                                                                                       |
  Hash for dependent task packagegroups/packagegroup-rpi-test.bb:do_package changed from 90d4d6b4f44b5c02560c4fd3a1d6143d7c79e75a110db351c99d393a58b5cf26 to 32d7a96f98179695ff0dce057a8501a6920ce7f053a47c3bd6bd50613bd2618b                                            |
  Unable to find matching sigdata for /OE/build/luneos-master/webos-ports/meta-raspberrypi/recipes-core/packagegroups/packagegroup-rpi-test.bb:do_package with hashes 90d4d6b4f44b5c02560c4fd3a1d6143d7c79e75a110db351c99d393a58b5cf26 or 32d7a96f98179695ff0dce057a8501a|
  6920ce7f053a47c3bd6bd50613bd2618b                                                                                                                                                                                                                                      |

* MACHINE_EXTRA_RRECOMMENDS in RRECOMMENDS_${PN} is MACHINE specific, e.g. between raspberrypi2 and raspberrypi3:

  tmp-glibc/sstate-diff/1580322520/raspberrypi2/all-webos-linux/packagegroup-rpi-test/1.0-r0.do_package.sigdata.90d4d6b4f44b5c02560c4fd3a1d6143d7c79e75a110db351c99d393a58b5cf26
  tmp-glibc/sstate-diff/1580322520/raspberrypi3/all-webos-linux/packagegroup-rpi-test/1.0-r0.do_package.sigdata.32d7a96f98179695ff0dce057a8501a6920ce7f053a47c3bd6bd50613bd2618b

  bitbake-diffsigs tmp-glibc/sstate-diff/1580322520/raspberrypi*/*/packagegroup-rpi-test*/*do_package.sig*                                                                                                    |
  NOTE: Starting bitbake server...
  basehash changed from ee2d20ddb4aa98ffefe5c4c56ba2e59833ba94ed3a4523d3e52683209626aa23 to ca3df8d8ef86b298f57c41ffba278dd0330ffb00e7e25943c272c8b3c57a6dc3
  Variable MACHINE_EXTRA_RRECOMMENDS value changed:
  "  kernel-modules udev-rules-rpi {+    linux-firmware-rpidistro-bcm43430     linux-firmware-rpidistro-bcm43455     bluez-firmware-rpidistro-bcm43430a1-hcd     bluez-firmware-rpidistro-bcm4345c0-hcd +}"

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>