rpidistro-vlc: update PACKAGECONFIG
Problem:

ERROR: Nothing PROVIDES 'gtk+3' (but rpidistro-vlc_3.0.12.bb
DEPENDS on or otherwise requires it)
gtk+3 was skipped: one of 'wayland x11' needs to be in DISTRO_FEATURES

If neither are included gtk+3 wont be included in sysroot of recipe.

Solution:

Only enable libnotify if either wayland or x11 present
in DISTRO_FEATURES.

Signed-off-by: Vincent Davis Jr <vince@underview.tech>